# Generated by Django 4.2.1 on 2023-05-09 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='student',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
