# Generated by Django 4.2.1 on 2023-05-09 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_remove_attendance_student_delete_student'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Course',
            new_name='Student',
        ),
        migrations.RenameField(
            model_name='attendance',
            old_name='course',
            new_name='student',
        ),
    ]
